name: Check Booking Status

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev libasound2 libatk-bridge2.0-0 libatspi2.0-0 \
          libgtk-3-0 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libgbm1 \
          libpangocairo-1.0-0 libpango-1.0-0 libcups2

    - name: Install Node.js dependencies
      run: npm install

    - name: Run scraper
      run: node check_booking.js
